title: Kitsu Status
short_title: Kitsu Status
name: kitsu
description: Status alerts for Kitsu, an anime & manga tracker.
baseUrl: https://status.kitsu.io/
defaultLocale: en
theme:
  scheduled:
    position: aboveGlobalStatus
  links:
    en:
      home: https://kitsu.io
      support: mailto:help@kitsu.io
      privacy: https://kitsu.io/privacy
      legal: https://kitsu.io/terms
locales:
  - code: en
    iso: en-US
    name: English
    file: en.json
content:
  frontMatterFormat: yaml
  systems:
    - api
    - cdn
    - dns
    - feeds
    - sync
    - import
