title: Kitsu Status
name: kitsu
description: Anime & Manga Tracker
baseUrl: https://status.kitsu.io/
defaultLocale: en
theme:
  scheduled:
    position: aboveGlobalStatus
  links:
    home: https://kitsu.io
    support: mailto:help@kitsu.io
    privacy: https://kitsu.io/privacy
    legal: https://kitsu.io/terms
locales:
  - code: en
    iso: en-US
    name: English
    file: en.json
content:
  frontMatterFormat: yaml
  systems:
    - api
    - feeds
    - sync
    - import
